title: WIMMA Blog
baseurl: "/blog"
exclude: ['README.md']
gems: [jekyll-paginate-v2]
pagination:
    enabled: true
    per_page: 4
    permalink: "blog/page/:num/"
    sort_reverse: true

markdown: kramdown
